### ISSUE TITLE
can not run docker deployment

### ISSUE THREAD

**Issue by xcorp1986** [JetBrains/phpstorm-workshop#32]
Hi,I have docker installed correctly,but when I add run configuration in phpstorm and run,the following message raising
Deploy log
Deploying 'Compose:  docker-compose.yml'...
Failed to deploy 'Compose:  docker-compose.yml': Cannot run program "docker-compose" (in directory "D:\project\docker-example"): CreateProcess error=2, 系统找不到指定的文件。
![image](https://cloud.githubusercontent.com/assets/3236975/25845647/483e3252-34e1-11e7-83fd-f8064f6d6549.png)

**Comment by xcorp1986** [comment]
Additional,the executable program 'docker-compose' is install include in docker latest windows version

**Comment by MaXal** [comment]
Sorry for the delay. Could you please do the following?
* install PhpStorm 2017.2 Public Preview: https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Early+Access+Program ?
* Open `Settings|Build, Execution,Deployment|Docker|Tools` and provide a full path to `docker-compose` there

**Comment by xcorp1986** [comment]
@MaXal Thx!It works~**docker-compose** should be full path definition，default it's "C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe"

**Comment by xcorp1986** [comment]
the issue can be closed，thx~

**Comment by RobsonKarls** [comment]
Work with Rider, RubyMine and PhpStorm

Go to : / Preferences / Build,Execution,Deployment / Docker / Tools
Make sure that the "Docker Compose executable:" field contains the complete path where docker compose is installed into.
How to determine the complete path:
run "which docker-compose"
note the full path for docker-compose; i.e.,       "/usr/local/bin/docker-compose"
Click "Apply", Then click "OK"

docker-compose will now properly be executed when you "Run" the "docker deployment" configuration.
