### ISSUE TITLE
08_Testing bug

### ISSUE THREAD

**Issue by marceldobrica** [JetBrains/phpstorm-workshop#43]
Hello,

In 08_Testing/02_Runing_tests is written:
//      From the Settings | Languages & Frameworks | PHP | Test Frameworks | PHPUnit,
// set workshop\08_Testing\Code\Bootstrap.php as the default bootstrap file.

I have tried different configuration and for me only works 
// set /opt/project/workshop/08_Testing/Code/Bootstrap.php as the default bootstrap file or
// set Code/Bootstrap.php as the default bootstrap file
otherwise Boostrap.php file could not be found...
![selection_130](https://user-images.githubusercontent.com/3274512/36018497-9e852612-0d84-11e8-80cb-bb9af266efdd.png)

**Comment by MaXal** [comment]
Fixed, thank you for the issue!
