### ISSUE TITLE
Misconfusion in docker-compose.yml

### ISSUE THREAD

**Issue by ajescode** [JetBrains/phpstorm-workshop#60]
https://github.com/JetBrains/phpstorm-workshop/blob/9a177fa9d2a209ee802334d0a9d7f2ab1c28b014/docker-compose.yml#L25

This line confuses new users. Volume for Linux should be also uncommented.

https://stackoverflow.com/questions/62104686/getting-started-with-phpstorm/62112810#62112810

**Comment by zeitgen** [comment]
addressed this in 6aee7aab72125611330c8606ed6f425d805c5726
