### ISSUE TITLE
mysql database missing

### ISSUE THREAD

**Issue by jenvigo** [JetBrains/phpstorm-workshop#65]
I follow the steps of the file:
workshop/10_Database/01_Connecting_to_a_database.md
But I cannot see the jetbrains database after that. Is that part working?

**Comment by DmitryTronin** [comment]
Sorry for missing the report. If possible, please open the project again, then in Database Tool window select the connection & click on a "Data Source Properties" button:
![image](https://user-images.githubusercontent.com/33625946/113704579-9a433780-96dc-11eb-9d0a-8a2284f8cfca.png)

Check if you have any error messages or warnings there.
