### ISSUE TITLE
Navigation / Navigate to class - "non-project" unclear

### ISSUE THREAD

**Issue by bradbulger** [JetBrains/phpstorm-workshop#67]
In 1.3_Navigate_to_class.md it says

> Check the Include non-project classes check box and open the ArrayObject (PHP SPL library) class. By default PhpStorm only searches classes inside your project, not your dependencies in the vendor folder.

Command+O opens a search window on the "Classes" tab. There is no "include non-project classes" check box that I could find.

After some travels through the Google and randomly trying things in the app, i found that if you choose the "All" tab, you get a checkbox for "Include non-project items", and the setting there seems to stick when you go back to the "Classes" tab.

I guess the app is moving faster than the workshop pages, but I'm not sure of a good way to explain all of that.

This is in PhpStorm 2021.1.3 Build PS-211.7442.50 from 2 June 2021, on MacOS

**Comment by ASauer** [comment]
This should be removed from this lesson (1.3) and moved to lesson 1.6, which is where this instruction applies. (so double-click shift and the correct page opens).

**Comment by zeitgen** [comment]
Indeed, the exercise is now moved to 1.6 (_Search Everywhere_).
