### ISSUE TITLE
Navigate to Symbol: JavaScript filter is not called JavaScript

### ISSUE THREAD

**Issue by ASauer** [JetBrains/phpstorm-workshop#68]
Lesson 1.5: 
Use filters
Filter to only search in JavaScript files and find the celebrateBirthday() function in the Customer.js file.

The filter is actually called ECMAScript 6

That was not intuitive, so it should be stated that this filter should be used.
It's good to know this 'subtle' difference exists...

**Comment by zeitgen** [comment]
Hi @ASauer! 
Thanks for reporting – this is indeed counterintuitive. There's a similar report in our issue tracker - [WEB-48897](https://youtrack.jetbrains.com/issue/WEB-48897) - please feel free to vote to get notified on updates.
