### ISSUE TITLE
Search Everywhere: type _name should be removed

### ISSUE THREAD

**Issue by ASauer** [JetBrains/phpstorm-workshop#69]
Lesson 1.6
Use recent files
Navigate to the $_name protected variable in Customer.php (type _name).

If you type this, nothing will be found, which is a bug, or good to know...
I think the idea is that you don't have to type anything, and you will see Customer.php among the recent files.

**Comment by zeitgen** [comment]
Hi @ASauer!

This actually works fine for me, given that `Customer` is indeed in the recent files list after completing lesson 1.3:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/5338707/133089549-41f5af9c-787e-4283-b934-45b8e35f05c5.png">

**Comment by ASauer** [comment]
Now I see, thx!
