### ISSUE TITLE
Escape on Mac does not clear highlights

### ISSUE THREAD

**Issue by ASauer** [JetBrains/phpstorm-workshop#70]
lesson 5.1
I can't find a shortcut that sets this as a key, so basically, for me, there is no way to unhighlight.

**Comment by zeitgen** [comment]
Hi @ASauer!

This one works fine for me. Another way to unhighlight is to use the same shortcut (`Shift+Command+F7`). 
As for `Escape`, could you please verify that it's mapped properly under _Keymap | Editor Actions | Escape_?

<img width="892" alt="image" src="https://user-images.githubusercontent.com/5338707/133094064-1c4f7495-8c29-470b-bbef-796fe66fb751.png">

**Comment by ASauer** [comment]
Now I know what I missed: At the top of the file there are instructions, but when I open a file, this command is 'collapsed'. I saw what appeared to me as highlights, but in fact these were not highlighted, since I did not use the shortcut that was mentioned in the 'collapsed' comment. Maybe a remark about this should be in the very first lesson!
Now Escape works as expected.

I already found Escape in the shortcuts, but since it did not appear to work, I thought there might be another shortcut with Escape for this, which I, of course, did not find.

**Comment by zeitgen** [comment]
Wow thanks for sharing!

> Maybe a remark about this should be in the very first lesson!

Definitely worth considering.

In the meantime, you can go to `Preferences | Editor | General | Code Folding` and disable folding for `File header` - i suspect you've got this enabled. This would expand those regions once and for all =)

![image](https://user-images.githubusercontent.com/5338707/133124334-df8a4687-27b2-4e09-a921-f2ac14f50089.png)

**Comment by ASauer** [comment]
Thanks for this tip! It is always hard to predict what a newbie will run into :)
