### ISSUE TITLE
03 Inspections 01 Highlights: Suppress for statement?

### ISSUE THREAD

**Issue by ASauer** [JetBrains/phpstorm-workshop#73]
I don't understand what is meant with 'Suppress for statement'.

I can choose 'Typo rename to...', but there is no 'Suppress for statement'

    // 7. A warning highlight is shown on the misspelled variable "$mispelled".
    //    Suppress the inspection for this statement only using Show Intention Actions |  Typo rename to...
    //         | Suppress for statement

It's a typo, or it is not clear what is supposed to happen, or it is not clear what I am supposed to do.

**Comment by zeitgen** [comment]
Looks like you're missing the extra options list, opens when you click `>` or press `Right`:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/5338707/133579848-036fbc35-f869-439b-9d3a-ba6c7aaabe83.png">

**Comment by ASauer** [comment]
thx!
