### ISSUE TITLE
03 Inspections: 08 Run Inspections: Where is the 'Inspection profile dropdown'?

### ISSUE THREAD

**Issue by ASauer** [JetBrains/phpstorm-workshop#76]
Create a custom Inspection profile in which only a few inspections are enabled.
HINT: Use the [...] next to the Inspection profile dropdown to enable or disable inspections in the selected profile.

I've searched in Settings, looked at the Code menu, looked at the interface...
Where is the 'Inspection profile dropdown'?

**Comment by zeitgen** [comment]
Well, here it is =) It's not in the settings, it's _Code | Inspect Code..._ as the exercise suggests:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/5338707/133585499-a43ff1f0-4ce9-4ec6-92a8-3375d981bfc2.png">

**Comment by ASauer** [comment]
Aha! Reading this:
`Run inspections on the Whole project.`
I clicked on OK in this dialog since I interpreted 'Run' as a command to Run something.

Maybe this text should say `Select` instead of 'Run'.

**Comment by zeitgen** [comment]
Well, it can be both: the [...] button simply takes you straight to the Inspections settings, which are otherwise accessible via _Preferences | Editor | Inspections_. So you can start with the default profile, then tweak it and run the inspections again, and so on.
